### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'prototype')     at sax.js:222:46

### ISSUE THREAD

**Issue by baiyajin** [wanglin2/mind-map#307]
TypeError: Cannot read properties of undefined (reading 'prototype')
    at sax.js:222:46
    at node_modules/.pnpm/registry.npmmirror.com+sax@1.2.4/node_modules/sax/lib/sax.js (sax.js:1565:1)
    at __require2 (chunk-AUZ3RYOM.js?v=71ca0ce9:18:50)
    at node_modules/.pnpm/registry.npmmirror.com+xml-js@1.6.11/node_modules/xml-js/lib/xml2js.js (xml2js.js:1:11)
    at __require2 (chunk-AUZ3RYOM.js?v=71ca0ce9:18:50)
    at node_modules/.pnpm/registry.npmmirror.com+xml-js@1.6.11/node_modules/xml-js/lib/index.js (index.js:3:14)
    at __require2 (chunk-AUZ3RYOM.js?v=71ca0ce9:18:50)
    at xmind.js:2:24

![image](https://github.com/wanglin2/mind-map/assets/49177898/e0e6671b-1f38-4c37-912c-f09c831dec82)

**Comment by baiyajin** [comment]
注释掉simple-mind-map组件，页面就能正常加载

**Comment by wanglin2** [comment]
https://github.com/Leonidas-from-XIV/node-xml2js/issues/651

可以参考这个解决
