### ISSUE TITLE
Cannot read properties of undefined (reading 'expand')

### ISSUE THREAD

**Issue by shenxj1228** [wanglin2/mind-map#58]
麻烦帮忙看一下，导入之后运行demo代码报错
vite :2.4.4
vue：3.2.11

import MindMap from "simple-mind-map/dist/simpleMindMap.umd.min"
 const mindMap = new MindMap({
                el: document.getElementById('file'),
                data: {
                    "root": {
                        "data": {
                            "text": "根节点"
                        },
                        "children": []
                    }
                }
            });
浏览器报错
Uncaught TypeError: Cannot read properties of undefined (reading 'expand')
    at mi.handleData (simpleMindMap.umd.min.js:287:212968)
    at new mi (simpleMindMap.umd.min.js:287:211255)
    at yi.createNode (simpleMindMap.umd.min.js:287:228229)
    at i2 (simpleMindMap.umd.min.js:287:230476)
    at w (simpleMindMap.umd.min.js:287:62812)
    at yi.computedBaseValue (simpleMindMap.umd.min.js:287:230421)
    at Array.<anonymous> (simpleMindMap.umd.min.js:287:230297)
    at i2 (simpleMindMap.umd.min.js:287:64420)
    at M (simpleMindMap.umd.min.js:287:64454)
    at yi.doLayout (simpleMindMap.umd.min.js:287:230396)

**Comment by shenxj1228** [comment]
我改成
` 
const mindMap = new MindMap({
                el: document.getElementById('file'),
                data: {
                    "data": {
                        "text": "根节点"
                    },
                    "children": []
                }
            });

`
就好了

**Comment by wanglin2** [comment]
抱歉，是我文档有误，我改一下。
